### ISSUE TITLE
[Summoner by Name] Non existing summoners are ignored without any notice

### ISSUE THREAD

**Issue by MakersF** [robrua/cassiopeia#10]
If you call
get_summoners_by_name(summoners)

and summoners is a list, if some summoners do not exists the result will simply ignore them.

Is this supposed to happen?

To check if there was any missing summoner the length of the names and the result can be compared. I'm hesitant to make a pull request as I don't know if this is intended, or do you believe it might be good to raise an exception (personally I don't think it's a good idea) or warn the user (to define how. print a warning if print_calls is on?)

**Comment by robrua** [comment]
Assuming you're talking about baseriotapi, this is intended. As I mentioned in #9, baseriotapi is intended to meet the API specs exactly and do no extra work (other than converting into python types and rate limiting). It's supposed to be a minimal wrapper for using the Riot API in a python typesystem.

On the core side, riotapi is supposed to return None for any summoner that didn't exist in a query for multiple summoners. Actually, there was a bug in that code that I noticed thanks to this issue, so all-in-all a success in my books =D.
