### ISSUE TITLE
Rate limiters "leaks" calls

### ISSUE THREAD

**Issue by MakersF** [robrua/cassiopeia#16]
Testing a (single-threaded) script of mine I got blacklisted( 2 times!!)
![overflow of limit](https://cloud.githubusercontent.com/assets/988456/10121098/d6cb8528-64dc-11e5-9b1c-b846d5cb032f.png)

Did not make any call from the web interface. Just run the program and went to sleep. (No API calls in the previous hours either).
All the requests went through the baseriotapi.

I don't think the problem is related to https://github.com/robrua/cassiopeia/pull/14 , as my program is not multi thread and thus there can not happen the race condition.

At a first glance I can not spot the problem, but I'm not really an export in python threading.

**Comment by jjmaldonis** [comment]
We have been using it for a month straight without a single problem. You are going to have to dig into what is going on in your case more seriously before we spend hours looking for a problem that may not exist.

**Comment by MakersF** [comment]
Suggestions about how to test it?
I actually tested the rates classes quite extensively, but didn't find
strange behaviours.
Built a couple of reproducible test cases, but found out a problem in them,
so I didn't post them.

May i ask you what is your usage pattern? Do you do some calls on user
request or are you always at the limit?
How do you handle urllib exceptions?
Have you experienced 503 responses, 404 responses on valid URLs(later
tasted on the browser), gaiaerror [errno -2]?
It might be about how I handle exceptions.

All of this could be useful in finding out the problem!
Il 27/set/2015 07:33, "jjmaldonis" <notifications@github.com> ha scritto:

**Comment by jjmaldonis** [comment]
>Suggestions about how to test it?

I think you have two options here. One would be to build your own rate limiter and run it on top of the baseriotapi one. The baseriotapi rate limiter should be checked first, and if the request is allowed then the code should then check your rate limiter. If you find differences between the two then there is a problem with one of them.  Another option would be to take the numbers that you are inputing into the baseriotapi rate limiter (and getting blacklisted for) and multiply those numbers by 0.5. Use the lower numbers for testing, and run a quick calculation to see if the calls are actually goes over the new rate limits.

>I actually tested the rates classes quite extensively, but didn't find  strange behaviours.  Built a couple of reproducible test cases, but found out a problem in them, so I didn't post them.

So you tested the rates classes extensively, but couldn't find a problem and you still posted an issue? This was why I said in my earlier comment that we are not going to spend hours looking for a problem that may not exist.  We have to be able to reproduce the problem for something like this.

>May i ask you what is your usage pattern? Do you do some calls on user request or are you always at the limit?  How do you handle urllib exceptions?  Have you experienced 503 responses, 404  responses on valid URLs(later tasted on the browser), gaiaerror [errno -2]?

We are always at the rate limit.  In general for handing exceptions, if we can an error code that can be retried then we retry it once.  If it fails again we just move on.

>It might be about how I handle exceptions.

This would be my bet as well but I haven't seen your code.  Are you waiting for long enough before retrying?  If you are constantly making calls then sometimes you will have to wait for that 10-minute rate limit and not just the 10-second one.  Maybe it's a bug in cass, or maybe it's a bug in your code.  If you can find a way to fully reproduce (and show us that you have reproduced it) it then we are happy to take a look.

**Comment by MakersF** [comment]
> So you tested the rates classes extensively, but couldn't find a problem

I tested the rate limiters. The look like they work as expected with a function which does not throw exceptions.
Here some of the code
```python
from cassiopeia.type.api.rates import MultiRateLimiter
import itertools
import datetime
l = MultiRateLimiter((10,0.1),(500, 6))
q = itertools.count()
def foo(c): next(c)
c=datetime.datetime.now()
for i in range(10000):
 l.call(foo, q)
l.wait()
t=datetime.datetime.now()
print(next(q),"calls in",(t-c).total_seconds(),". Expected 10000 in at least 120s")
```
This does not rule out every possible bug.

> Another option would be to take the numbers that you are inputing into the baseriotapi rate limiter (and getting blacklisted for) and multiply those numbers by 0.5. 

My last blacklisting happened with `baseriotapi.set_rate_limits((10, 12), (490, 600))`.
I'm now running with (5,10),(250,600). I'll write it here if it exceeds the limit.

> We are always at the rate limit. In general for handing exceptions, if we get an error code that can be retried then we retry it once. If it fails again we just move on.

Whatever error I get I ignore it, sleep for a few seconds (in case the network had problems and went down for a few moments, or you temporarily disconnected from wifi) and then continue.

> So you tested the rates classes extensively, but couldn't find a problem and you still posted an issue? 

The API states that it limits the calls. I call only from the API. The limit is exceeded. To me, it looks like the library is "not fulfilling" the "contract". It might be a problem of the library, it might be a problem of my code. If it's the library, would be nice to fix it. If it's my code, then we should document that some uses actually exceed the rate limit. That's why I opened an issue anyways.

>  If you can find a way to fully reproduce (and show us that you have reproduced it) it then we are happy to take a look.
Right now, on my machine, the behaviour was 100% reproducible. Testing now halving the calls to test if that happens again. If it does, I'll load the code on github and link it here. I planned to open source it anyways, so it's not a problem. The usage on your part to reproduce will be really easy: just start a script

**Comment by MakersF** [comment]
![overflow3](https://cloud.githubusercontent.com/assets/988456/10123816/a5f837c2-6543-11e5-9bc8-de01fb2fa038.png)

That happened with
`baseriotapi.set_rate_limits((5, 10), (250, 600))`
It shouldn't do more than 250 calls/10mins

**Comment by robrua** [comment]
I haven't tested the rate classes particularly extensively - I wouldn't discount the possibility that there's a bug in them, but they seem to behave as intended in the testing I have done.

I haven't been blacklisted ever under this rate limiting running @ full dev key limit (10,10), (500,600).

I don't really have a clue why you'd end up with call graph numbers over 250/7mins with that limit though. One thing worth noting is that I don't fully understand how Riot's rate limiting works. It doesn't sync 100% with the rate limiter (nor with the Java version, which is much more thoroughly tested and I'm confident is very accurate), so occasionally the lib will receive a 429 if they get unsynced and will resync itself. Thing is, if this happens you're going to get fewer calls than your limit, so I'm not sure how you're ending up with more here.

I'd try tracking your call count client-side and seeing if it agrees with Riot's numbers.
Is there any client-side error you're running in to or is it just blacklisting + unexpectedly high call counts?

I'm interested to see the code you're using as well - the error handling might have something to do with it, though it sounds like what you're doing above shouldn't cause problems.

Let me know what you find out - there could be a bug but I don't really have anything to go off of to find it thus far.

**Comment by MakersF** [comment]
Well, I guess the bars are off a few minutes. I mean that each bar represents 10mins time slots, not only 7 (even if they look like. It's probably to distinguish them. If i plot a line it is consistent with that).
I thought it could be my exception handling code, but after removing it the behaviour is the same.

I'll load the code and post the link here, as well as log the api calls
![overlow4](https://cloud.githubusercontent.com/assets/988456/10124096/0ff8e286-654c-11e5-9bc4-a6bc6f083d85.png)

**Comment by MakersF** [comment]
Here is the code.
https://github.com/MakersF/RiotScraper

call main.py passing the path to this json.
http://www.pasteall.org/61362/javascript

Put in the same directory of the json above this json file (it's just to have more seed players)
http://www.pasteall.org/61363/javascript

You need to set your api key and the destination directory for the stored files (.gz files. 5000 matches weight about 3mb so you won't have problems,as you'll download less than 100)

If you want to set a rate limiter different from the default one, I'd suggest to put it at line 15.

Let me know if you encounter my problems

**Comment by MakersF** [comment]
Here is the log of the requests
http://www.pasteall.org/61365/text

Here is the graph
![overflow5](https://cloud.githubusercontent.com/assets/988456/10124327/b593fd6a-6552-11e5-958c-a6cb0cc4e015.png)

Looks like the requests are actually correct.

Tested it 2 times..

So is it a problem on riot part?

**Comment by robrua** [comment]
Hard to say - my guess is that the API call tracking may not be super precise. It's also possible that Cass is sending a few extra requests - 429s do occasionally come in when the rate limiter gets desynced from Riot's, and you'll end up w/a few more calls.

Keep me updated if you find out something else about this - I'm worried if people are getting blacklisted while using it, but if it's just a few extra calls due to limiter desync I don't think there's really a way to avoid those, since you can't really sync 100% reliably w/o a vector clock or something.

For now I'm not going to make any changes. If you find out what the problem you were having was and it's in Cass let me know and we can iron it out.

**Comment by MakersF** [comment]
I agree with you. It looks like we can't do much to mitigate the issue (I'll run with a stricter limiter in future just to avoid problems).

I'll probably open a thread asking more info on the developer site, i'll link any new here!

**Comment by robrua** [comment]
One note for running a strict limit - I give cass my full limit to work with and haven't ever been blacklisted @ full utilization. If you need to use a stricter limit to not get blacklisted there's definitely a problem in cass

**Comment by MakersF** [comment]
I measured it several time, cassiopeia is doing the exact number of calls!
I have no idea why riot counts more calls. I just can't risk being blacklisted permanently. Not a big deal to run at 490 instead of 500

**Comment by robrua** [comment]
Alrighty, sounds good

**Comment by sbrodehl** [comment]
So I got blacklisted 449 times in the last 6 hours, despite setting the right rate limits.
I am aware that it is possible that Cass is sending a few extra requests, but it seems that there is some kind of issue. Not sure if it is an error in the code or just a too optimistic calculation.
Isn't riot returning some additional headers with a 429 response and sends the remaining seconds before the rate limit resets? I know Cass will retry after the given time so ... no idea why the limit is exceeded.
Is there any news?

**Comment by MakersF** [comment]
Did you get actually blacklisted or did you juat go over the limit?

I got over the limit 13000 times in the last week according to my dashboad,
but I never got blacklisted.

I checked extensively and Cassiopeia is correctly throttling the requests.

So fear not and just ignore the messages on your board, they are useless.

But be sure to make requests only through Cassiopeia. If you are doing some
manually or you have 2 different processes that might cause the problem.

To wrap up, you go over the limit when you get a 429 reply, not when the
dashboard says so. In the last week I got it only once and that's when I
made a manual request while my process was running
Il 20/nov/2015 07:37 AM, "Seb Bro" <notifications@github.com> ha scritto:

**Comment by robrua** [comment]
The was a bug added in during a recent commit. It's been fixed.

**Comment by sbrodehl** [comment]
@MakersF I didn't got blacklisted, just got the messages on my board. I did no manual requests and was wondering why the limit could be exceeded. Seems to me that riot is inconsistent with the return of 429 responses, so I agree with you on that one
> So fear not and just ignore the messages on your board, they are useless.
But in general I wouldn't advice to break given limits from 'business' partners. It is far more valuable to consistently query the API then retrieving more queries than the limit for a short time.

@robrua I will test the new version and report back if the limit is exceeded, thanks!

**Comment by jjmaldonis** [comment]
So if you both are getting messages on your board, but not receiving 429, I agree that there is something inconsistent going on on Riot's end. Do one of you guys want to make a bug post on the forums about it? I have a feeling they may not be aware of this.

**Comment by sbrodehl** [comment]
Even with the recent changes from @robrua I exceeded the limit "hundreds of times" according to my dashboard. The chart showed that I made around 560 calls per 10min twice.
Do Cass has some kind of debug mode where we can log all calls (+ timestamp, endpoint, request codes, current rate limit, etc.)? Since riot gives a 10min time frame and logs the call count we can compare and check things out.

**Comment by sbrodehl** [comment]
@MakersF Your api key is compromised, since you posted the log above!

**Comment by MakersF** [comment]
You can modify request.py. log alla the calls with the time, and check for
yourself. If you look into the closed issues, you will find mine stating
the same problem that dashboard is reporting over request. The point is
that as long as the server is not replying you with 429, you are fine.
Il 21/nov/2015 20:23, "Seb Bro" <notifications@github.com> ha scritto:

**Comment by MakersF** [comment]
@sbrodehl Thank you for notifying me, I changed my key
