### ISSUE TITLE
Issue with side attribute from participant (minor issue simple fix)

### ISSUE THREAD

**Issue by Re009372** [robrua/cassiopeia#19]
Hello, I've been playing around with your library, which is awesome by the way. After getting a current game and getting the list of participants out, I'm getting an error when trying to get the side of the participant. You can see in the provided screen shot. The compiler cannot find Side from the library because the constructor name is declared lowercase instead of uppercase in the return statement. Again thank you for making this library, if you would like any help with it I'd be glad to contribute.
![cassiopeia error](https://cloud.githubusercontent.com/assets/11260061/11016542/2b592df2-8553-11e5-857d-6a0ee5bad699.jpg)

**Comment by robrua** [comment]
True enough - I commented on the pull request #20 you made.

Thanks for the kind words about the library, I'm happy it's useful.

In terms of contributions, for now just bug-squashing is super helpful. After the tournament API, the next thing I'd like to change is to add configuration of what types are cached automatically by Cass. I don't have any specific plans on making this happen soon, though.
