### ISSUE TITLE
matchlistapi end_index fixed at +20

### ISSUE THREAD

**Issue by sbrodehl** [robrua/cassiopeia#21]
Hello there,
is there a reason why the end_index is hard coded with a fixed offset by 20 to the given begin_index in the matchlist API? See the code [here](https://github.com/robrua/cassiopeia/blob/master/cassiopeia/dto/matchlistapi.py#L22).

I did not find a limit for the returned games from riot, so I guess there is no reason to limit the requested batch?

**Comment by Re009372** [comment]
Because the match history of a summoner shows the last 20 games they've played, this was increased from 10 about 9-12 months ago.

**Comment by robrua** [comment]
the 20 game limit used to be enforced by the match-list endpoint on release. I'll be removing the limit soon.

**Comment by robrua** [comment]
Just committed a fix for this
