### ISSUE TITLE
Support tournament API

### ISSUE THREAD

**Issue by hankditton** [robrua/cassiopeia#41]
Are there plans to support the new tournament API?

https://developer.riotgames.com/docs/tournaments-api

**Comment by robrua** [comment]
In progress, as you can see from the most recent commit. Been super busy recently, but it'll be finished soon (tm). Probably right after the holidays.

**Comment by hankditton** [comment]
Awesome, thanks a lot for all of the hard work!

**Comment by zachcd** [comment]
Hello!  I'm a student developer working on a tournament app for my school club, just curious when cassiopeia will have tournament api support?  Should I look into implementing it on my own?  Our tournament will be starting in about a week, everything is set up except for the tournament api, so just curious what timeline I should expect.  Thank you for all of your hard work!

**Comment by robrua** [comment]
Hey - sorry to everyone waiting on this. I've been caught up spending my time on a lot of other stuff recently. It's really almost finished at this point, and just needs that final push. I'll try to set some time aside this week to finish it up. If I don't end up hitting your deadline, #45 seems like it should work, even though my version isn't going to look exactly like it.

**Comment by zachcd** [comment]
No problem at all!  Thank you for the fast response and this excellent library.

**Comment by robrua** [comment]
Sorry for the wait everybody. Just committed a mostly, but almost certainly not entirely working version of this. I haven't tested it since I don't have an active tournament API key. Working on getting that, but until then I've made the first pass available.

**Comment by robrua** [comment]
Alright - did some basic testing and have support for this completed now.
