### ISSUE TITLE
New Release before new LoL patch

### ISSUE THREAD

**Issue by MakersF** [robrua/cassiopeia#43]
Would it be possible to have a new release before the new patch hits the servers?

The addition of Rift Herald is quite noteworthy, and that means we can start collecting its data since the start of the patch.

**Comment by robrua** [comment]
Hey - should be putting out a release once I finish the tournament API soon (tm). Probably right after the holidays.

**Comment by MakersF** [comment]
That would be great!

**Comment by sbrodehl** [comment]
Riot doesn't provide patchnotes and API changes before they go live, so I guess there is no chance to release a new version before the patch hits the servers?!
But if one follows the PBE cycle maybe one can guess the new changes.

**Comment by MakersF** [comment]
Yeah,
But they are following something close to a 6 weeks release cycle, so we
know when we can expect a new patch.

I guess the time estimate Rob did is fine!
I have the code ready and tested, I just need the release before the
deployment so not to much too much with virtualenvs on the servers

**Comment by robrua** [comment]
new release is finally done
