### ISSUE TITLE
SQLAlchemy as dependency?

### ISSUE THREAD

**Issue by Flakeee** [robrua/cassiopeia#46]
I'm wondering why SQLAlchemy is a dependency. I looked at the code and it seems like it's only used when SQLAlchemy is actually installed, but works perfectly without it. Still, it's automatically installed over pip even though it's not needed.

I like this API more than the others since it's activately in development, but since I want to use it in a Django application with Django database models, I have no use for the SQLAlchemy support.

**Comment by robrua** [comment]
#4 #24
