### ISSUE TITLE
Matchlist and season

### ISSUE THREAD

**Issue by hijaek** [robrua/cassiopeia#47]
I want a list of games that I've played in season 2015. 

from cassiopeia import riotapi
riotapi.set_region("NA")
riotapi.set_api_key("6d5b2d52-bbb2-4540-aab8-cdf82e1e2c13")

summoner = riotapi.get_summoner_by_name("dyrus")
mylist = riotapi.get_match_list(summoner, seasons="SEASON2015")

Unfortunately, I am getting "AttributeError: 'str' object has no attribute 'value'"

Have I not imported something properly?

**Comment by sbrodehl** [comment]
```seasons``` is a ```Season``` or a ```list<Season>```, so you can use ```Season.season_5``` from the enum in ```cassiopeia.type.core.common``` or provide a list of those:
```python
from cassiopeia.type.core.common import Season
from cassiopeia import riotapi

riotapi.set_region("NA")
riotapi.set_api_key("API-KEY")

summoner = riotapi.get_summoner_by_name("dyrus")
mylist = riotapi.get_match_list(summoner, seasons=Season.season_5)
```
Also you should change your API key because this one is now compromised.
Anyway I guess a proper string -> Season conversion is needed here.

**Comment by sbrodehl** [comment]
PR #48 implements better error messages.
Should we check ```Champion`` and ```Summoner``` values the same way?

**Comment by jjmaldonis** [comment]
Well shoot. I just made a fix to allow strings as input for season and queues for the matchlist endpoint. Sorry @sbrodehl, that was unfortunate timing. :neutral_face: However, I didn't implement the same functionality for the other apis if you would like to do so. At some point that should be done. Closes #48

**Comment by jjmaldonis** [comment]
Also, I forgot to answer your question. You are right that you could check Champion and Summoner values and throw an error if they are the wrong type. However, I did not implement the string-to-object implementation for these because it could require an addition api call. But yes, throwing an error is a good idea.

**Comment by sbrodehl** [comment]
@hijaek please change your key or at least edit your post above!

**Comment by hijaek** [comment]
done. thanks
