### ISSUE TITLE
get_ranked_stats  from cassiopeia/cassiopeia/core/statsapi.py

### ISSUE THREAD

**Issue by hijaek** [robrua/cassiopeia#51]
https://github.com/robrua/cassiopeia/blob/789e354bbcd1e091c50c8c562adfc64ff69d5133/cassiopeia/core/statsapi.py

I get that this function will return 
{object of champ: object of my aggstat of that champ}

For example,
dyrus = riotapi.get_summoner_by_name("dyrus")
dyrusstat=riotapi.get_ranked_stats(summoner=dyrus, season=Season.season_5)

Now, if I print(dyrusstat[object of champ]), I will get the agg stat of that object of champ. 

But I am not able to understand how to bring that object of champ. 

if I want to call how dyrus did for "Dr. Mundo". How can I index within this dictionary generated by the function?

I tried to bring a champ object by using cassiopeia.riotapi.get_champions_by_id() function, but didnt work. (i.e dyrusstat[cassiopeia.riotapi.get_champions_by_id(36)] where 36 is mundo id > this didn't work)

**Comment by robrua** [comment]
You'll want to use either riotapi.get_champion_by_id(36) or riotapi.get_champion_by_name("Dr. Mundo") to get the champion object for Mundo.
